zuul:
  routes:
    auth-server:
      path: /security/**
      serviceId: mud-microservice-security
      sensitive-headers:
ribbon:
  eureka:
    enabled: false
  eager-load:
    enabled: false
spring:
  profiles:
    active: pro