spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: mud-microservice-configcenter
      name: security
eureka:
  client:
    service-url:
      defaultZone: http://admin:111111@peer1:8761/eureka/,http://admin:222222@peer2:8762/eureka/,http://admin:333333@peer3:8763/eureka/
security:
  user:
    password: password
  oauth2:
    client:
      client-id: mud
      client-secret: mud
      scope: read, write
      auto-approve-scopes: .*
    authorization:
      check-token-access: permitAll()
logging:
  level:
    root: debug