spring:
  application:
    name: mud-microservice-eureka
---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://admin:123456@peer2:8762/eureka/,http://admin:123456@peer3:8763/eureka/
    healthcheck:
      enabled: true
security:
  user:
    name: admin
    password: 123456
server:
  port: 8761
---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://admin:123456@peer3:8763/eureka/,http://admin:123456@peer1:8761/eureka/
    healthcheck:
      enabled: true
security:
  user:
    name: admin
    password: 123456
server:
  port: 8762
---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://admin:123456@peer1:8761/eureka/,http://admin:123456@peer2:8762/eureka/
    healthcheck:
      enabled: true
security:
  user:
    name: admin
    password: 123456
server:
  port: 8763