spring:
  application:
    name: mud-microservice-eureka
---
spring:
  profiles: eureka1
eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://admin:222222@eureka2:8762/eureka/,http://admin:333333@eureka3:8763/eureka/
    healthcheck:
      enabled: true
security:
  user:
    name: admin
    password: 111111
server:
  port: 8761
---
spring:
  profiles: eureka2
eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://admin:333333@eureka3:8763/eureka/,http://admin:111111@eureka1:8761/eureka/
    healthcheck:
      enabled: true
security:
  user:
    name: admin
    password: 222222
server:
  port: 8762
---
spring:
  profiles: eureka3
eureka:
  instance:
    hostname: eureka3
  client:
    service-url:
      defaultZone: http://admin:111111@eureka1:8761/eureka/,http://admin:222222@eureka2:8762/eureka/
    healthcheck:
      enabled: true
security:
  user:
    name: admin
    password: 333333
server:
  port: 8763