spring:
  application:
    name: mud-microservice-eureka
---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://admin:222222@peer2:8762/eureka/,http://admin:333333@peer3:8763/eureka/
    healthcheck:
      enabled: true
security:
  user:
    name: admin
    password: 111111
server:
  port: 8761
---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://admin:333333@peer3:8763/eureka/,http://admin:111111@peer1:8761/eureka/
    healthcheck:
      enabled: true
security:
  user:
    name: admin
    password: 222222
server:
  port: 8762
---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://admin:111111@peer1:8761/eureka/,http://admin:222222@peer2:8762/eureka/
    healthcheck:
      enabled: true
security:
  user:
    name: admin
    password: 333333
server:
  port: 8763