spring:
  cloud:
    config:
      discovery:
        service-id: mud-microservice-configcenter
        enabled: true
      name: activity
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/