package com.tony.demo.microservice.mud.trade.dao.entity;

public class RiskTestDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_risk_test.id
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_risk_test.question_no
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    private Integer questionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_risk_test.question_display_no
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    private Integer questionDisplayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_risk_test.question_content
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    private String questionContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_risk_test.option_no
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    private String optionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_risk_test.option_display_no
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    private Integer optionDisplayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_risk_test.option_content
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    private String optionContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_risk_test.option_score
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    private Integer optionScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_risk_test.question_type
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    private Integer questionType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_risk_test.id
     *
     * @return the value of fmall_risk_test.id
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_risk_test.id
     *
     * @param id the value for fmall_risk_test.id
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_risk_test.question_no
     *
     * @return the value of fmall_risk_test.question_no
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public Integer getQuestionNo() {
        return questionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_risk_test.question_no
     *
     * @param questionNo the value for fmall_risk_test.question_no
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public void setQuestionNo(Integer questionNo) {
        this.questionNo = questionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_risk_test.question_display_no
     *
     * @return the value of fmall_risk_test.question_display_no
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public Integer getQuestionDisplayNo() {
        return questionDisplayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_risk_test.question_display_no
     *
     * @param questionDisplayNo the value for fmall_risk_test.question_display_no
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public void setQuestionDisplayNo(Integer questionDisplayNo) {
        this.questionDisplayNo = questionDisplayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_risk_test.question_content
     *
     * @return the value of fmall_risk_test.question_content
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public String getQuestionContent() {
        return questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_risk_test.question_content
     *
     * @param questionContent the value for fmall_risk_test.question_content
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public void setQuestionContent(String questionContent) {
        this.questionContent = questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_risk_test.option_no
     *
     * @return the value of fmall_risk_test.option_no
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public String getOptionNo() {
        return optionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_risk_test.option_no
     *
     * @param optionNo the value for fmall_risk_test.option_no
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public void setOptionNo(String optionNo) {
        this.optionNo = optionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_risk_test.option_display_no
     *
     * @return the value of fmall_risk_test.option_display_no
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public Integer getOptionDisplayNo() {
        return optionDisplayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_risk_test.option_display_no
     *
     * @param optionDisplayNo the value for fmall_risk_test.option_display_no
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public void setOptionDisplayNo(Integer optionDisplayNo) {
        this.optionDisplayNo = optionDisplayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_risk_test.option_content
     *
     * @return the value of fmall_risk_test.option_content
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public String getOptionContent() {
        return optionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_risk_test.option_content
     *
     * @param optionContent the value for fmall_risk_test.option_content
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public void setOptionContent(String optionContent) {
        this.optionContent = optionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_risk_test.option_score
     *
     * @return the value of fmall_risk_test.option_score
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public Integer getOptionScore() {
        return optionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_risk_test.option_score
     *
     * @param optionScore the value for fmall_risk_test.option_score
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public void setOptionScore(Integer optionScore) {
        this.optionScore = optionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_risk_test.question_type
     *
     * @return the value of fmall_risk_test.question_type
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public Integer getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_risk_test.question_type
     *
     * @param questionType the value for fmall_risk_test.question_type
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    public void setQuestionType(Integer questionType) {
        this.questionType = questionType;
    }
}