package com.tony.demo.microservice.mud.trade.dao.mapper;

import com.tony.demo.microservice.mud.trade.dao.entity.RiskTestDO;

import java.util.List;
import java.util.Map;

public interface RiskTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmall_risk_test
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmall_risk_test
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    int insert(RiskTestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmall_risk_test
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    int insertSelective(RiskTestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmall_risk_test
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    RiskTestDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmall_risk_test
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    int updateByPrimaryKeySelective(RiskTestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmall_risk_test
     *
     * @mbggenerated Fri Oct 17 10:12:46 CST 2014
     */
    int updateByPrimaryKey(RiskTestDO record);
    
    /**
     * 查询测评选项
     * @param rt
     * @return
     */
    List<RiskTestDO> selectTestOptions(RiskTestDO rt);
    
    /**
     * 查询测试题目
     * @param rt
     * @return
     */
    List<RiskTestDO> selectTestQuestions(RiskTestDO rt);

    /**
     * 查询全部测试题目
     * @return
     */
    List<Map> selectAllTestQuestions();
}