spring:
  cloud:
    consul:
      host: localhost
      port: 8500
    config:
      server:
        git:
          uri: https://github.com/TonyLiu0112/mud-microservice-configuration-repository
          search-paths:
            - mud-microservice-*
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
encrypt:
  key-store:
    location: classpath:/server.jks
    password: mud#234
    alias: ConfigCenter
    secret: mudconfig#234