spring:
  application:
    name: mud-microservice-configcenter
  cloud:
      config:
        server:
          git:
            uri: https://github.com/TonyLiu0112/mud-microservice-configuration-repository
            search-paths:
              - mud-microservice-activity
              - mud-microservice-customer
              - mud-microservice-security
  rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/