package com.tony.demo.microservice.mud.trade.service.bean.req;

import java.util.Date;

public class Product {
   
    private Integer id;

    /**产品分类id*/
    private Integer pCateId;
    
    /**基金来源id**/
    private Integer patnId;

    /**基金产品编号**/
    private String jjcpbh;

    /**基金产品状态**/
    private Integer jjcpzt;

    /**申购费率**/
    private Double sgfl;

   /**赎回费率*/
    private Double shfl;

    /**管理费率**/
    private Double glfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.tgfl
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    /**托管费率**/
    private Double tgfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.jjcpmc
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    /**基金名称**/
    private String jjcpmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.jjgsmc
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    /**基金公司名称**/
    private String jjgsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.jjjl
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    /**基金经理**/
    private String jjjl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.jjgm
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    /**基金规模**/
    private Double jjgm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.clrq
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    /**成立日期**/
    private Date clrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.ljsgje
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    /**累积申购金额**/
    private Double ljsgje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.jrzrs
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    /**加入总人数**/
    private Integer jrzrs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.ljzqje
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    /**累积赚取金额**/
    private Double ljzqje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.ljgmcs
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    /**累积购买次数**/
    private Integer ljgmcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.sgsj
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    /**申购时间**/
    private Date sgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.cjsj
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    /**创建时间**/
    private Date cjsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.xgsj
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    /**修改时间**/
    private Date xgsj;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.id
     *
     * @return the value of fmall_product.id
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    
    private Integer isHot;
    
    private String subCategoryDesc;
    
    private String subCategoryCode;
    
    private String shareType;
    
    /**
     * X理财产品编号
     */
    private String productNo;
    
    /**
     * 产品规模
     */
    private double totalBalance;
    
    private int status;

    private double lowestAmount;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.id
     *
     * @param id the value for fmall_product.id
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.flwj
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    private String flwj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.tzfw
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    private String tzfw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.tzmb
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    private String tzmb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmall_product.xsjg
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    private String xsjg;
    
    /**
     * 七日年化利率
     */
    private Double qrnhlv;
    
    /**
     * 万份收益
     */
    private Double wfsy;

    /**
     * 费率
     */
    private String feeRate;
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIsHot() {
		return isHot;
	}

	public void setIsHot(Integer isHot) {
		this.isHot = isHot;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.p_cate_id
     *
     * @return the value of fmall_product.p_cate_id
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Integer getpCateId() {
        return pCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.p_cate_id
     *
     * @param pCateId the value for fmall_product.p_cate_id
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setpCateId(Integer pCateId) {
        this.pCateId = pCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.patn_id
     *
     * @return the value of fmall_product.patn_id
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Integer getPatnId() {
        return patnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.patn_id
     *
     * @param patnId the value for fmall_product.patn_id
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setPatnId(Integer patnId) {
        this.patnId = patnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.jjcpbh
     *
     * @return the value of fmall_product.jjcpbh
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public String getJjcpbh() {
        return jjcpbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.jjcpbh
     *
     * @param jjcpbh the value for fmall_product.jjcpbh
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setJjcpbh(String jjcpbh) {
        this.jjcpbh = jjcpbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.jjcpzt
     *
     * @return the value of fmall_product.jjcpzt
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Integer getJjcpzt() {
        return jjcpzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.jjcpzt
     *
     * @param jjcpzt the value for fmall_product.jjcpzt
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setJjcpzt(Integer jjcpzt) {
        this.jjcpzt = jjcpzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.sgfl
     *
     * @return the value of fmall_product.sgfl
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Double getSgfl() {
        return sgfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.sgfl
     *
     * @param sgfl the value for fmall_product.sgfl
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setSgfl(Double sgfl) {
        this.sgfl = sgfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.shfl
     *
     * @return the value of fmall_product.shfl
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Double getShfl() {
        return shfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.shfl
     *
     * @param shfl the value for fmall_product.shfl
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setShfl(Double shfl) {
        this.shfl = shfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.glfl
     *
     * @return the value of fmall_product.glfl
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Double getGlfl() {
        return glfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.glfl
     *
     * @param glfl the value for fmall_product.glfl
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setGlfl(Double glfl) {
        this.glfl = glfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.tgfl
     *
     * @return the value of fmall_product.tgfl
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Double getTgfl() {
        return tgfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.tgfl
     *
     * @param tgfl the value for fmall_product.tgfl
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setTgfl(Double tgfl) {
        this.tgfl = tgfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.jjcpmc
     *
     * @return the value of fmall_product.jjcpmc
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public String getJjcpmc() {
        return jjcpmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.jjcpmc
     *
     * @param jjcpmc the value for fmall_product.jjcpmc
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setJjcpmc(String jjcpmc) {
        this.jjcpmc = jjcpmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.jjgsmc
     *
     * @return the value of fmall_product.jjgsmc
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public String getJjgsmc() {
        return jjgsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.jjgsmc
     *
     * @param jjgsmc the value for fmall_product.jjgsmc
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setJjgsmc(String jjgsmc) {
        this.jjgsmc = jjgsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.jjjl
     *
     * @return the value of fmall_product.jjjl
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public String getJjjl() {
        return jjjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.jjjl
     *
     * @param jjjl the value for fmall_product.jjjl
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setJjjl(String jjjl) {
        this.jjjl = jjjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.jjgm
     *
     * @return the value of fmall_product.jjgm
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Double getJjgm() {
        return jjgm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.jjgm
     *
     * @param jjgm the value for fmall_product.jjgm
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setJjgm(Double jjgm) {
        this.jjgm = jjgm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.clrq
     *
     * @return the value of fmall_product.clrq
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Date getClrq() {
        return clrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.clrq
     *
     * @param clrq the value for fmall_product.clrq
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setClrq(Date clrq) {
        this.clrq = clrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.ljsgje
     *
     * @return the value of fmall_product.ljsgje
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Double getLjsgje() {
        return ljsgje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.ljsgje
     *
     * @param ljsgje the value for fmall_product.ljsgje
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setLjsgje(Double ljsgje) {
        this.ljsgje = ljsgje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.jrzrs
     *
     * @return the value of fmall_product.jrzrs
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Integer getJrzrs() {
        return jrzrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.jrzrs
     *
     * @param jrzrs the value for fmall_product.jrzrs
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setJrzrs(Integer jrzrs) {
        this.jrzrs = jrzrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.ljzqje
     *
     * @return the value of fmall_product.ljzqje
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Double getLjzqje() {
        return ljzqje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.ljzqje
     *
     * @param ljzqje the value for fmall_product.ljzqje
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setLjzqje(Double ljzqje) {
        this.ljzqje = ljzqje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.ljgmcs
     *
     * @return the value of fmall_product.ljgmcs
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Integer getLjgmcs() {
        return ljgmcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.ljgmcs
     *
     * @param ljgmcs the value for fmall_product.ljgmcs
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setLjgmcs(Integer ljgmcs) {
        this.ljgmcs = ljgmcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.sgsj
     *
     * @return the value of fmall_product.sgsj
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Date getSgsj() {
        return sgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.sgsj
     *
     * @param sgsj the value for fmall_product.sgsj
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setSgsj(Date sgsj) {
        this.sgsj = sgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.cjsj
     *
     * @return the value of fmall_product.cjsj
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.cjsj
     *
     * @param cjsj the value for fmall_product.cjsj
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmall_product.xgsj
     *
     * @return the value of fmall_product.xgsj
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmall_product.xgsj
     *
     * @param xgsj the value for fmall_product.xgsj
     *
     * @mbggenerated Thu Oct 02 15:59:22 CST 2014
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

	public String getFlwj() {
		return flwj;
	}

	public void setFlwj(String flwj) {
		this.flwj = flwj;
	}

	public String getTzfw() {
		return tzfw;
	}

	public void setTzfw(String tzfw) {
		this.tzfw = tzfw;
	}

	public String getTzmb() {
		return tzmb;
	}

	public void setTzmb(String tzmb) {
		this.tzmb = tzmb;
	}

	public String getXsjg() {
		return xsjg;
	}

	public void setXsjg(String xsjg) {
		this.xsjg = xsjg;
	}

	public Double getQrnhlv() {
		return qrnhlv;
	}

	public void setQrnhlv(Double qrnhlv) {
		this.qrnhlv = qrnhlv;
	}

	public Double getWfsy() {
		return wfsy;
	}

	public void setWfsy(Double wfsy) {
		this.wfsy = wfsy;
	}

	public String getSubCategoryDesc() {
		return subCategoryDesc;
	}

	public void setSubCategoryDesc(String subCategoryDesc) {
		this.subCategoryDesc = subCategoryDesc;
	}

	public String getSubCategoryCode() {
		return subCategoryCode;
	}

	public void setSubCategoryCode(String subCategoryCode) {
		this.subCategoryCode = subCategoryCode;
	}

	public String getShareType() {
		return shareType;
	}

	public void setShareType(String shareType) {
		this.shareType = shareType;
	}

	public String getProductNo() {
		return productNo;
	}

	public void setProductNo(String productNo) {
		this.productNo = productNo;
	}

	public double getTotalBalance() {
		return totalBalance;
	}

	public void setTotalBalance(double totalBalance) {
		this.totalBalance = totalBalance;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

    public double getLowestAmount() {
        return lowestAmount;
    }

    public void setLowestAmount(double lowestAmount) {
        this.lowestAmount = lowestAmount;
    }

    public String getFeeRate() {
        return feeRate;
    }

    public void setFeeRate(String feeRate) {
        this.feeRate = feeRate;
    }
}