spring:
  application:
    name: mud-microservice-web-manager
    index: 1
  cloud:
    config:
      discovery:
        enabled: true
        service-id: mud-microservice-configcenter
      name: web-manager
eureka:
  client:
    service-url:
      defaultZone: http://admin:111111@peer1:8761/eureka/,http://admin:222222@peer2:8762/eureka/,http://admin:333333@peer3:8763/eureka/
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: mud
      client-secret: mud
      access-token-uri: http://localhost:18808/sso-proxy/security/security/oauth/token
      user-authorization-uri: http://localhost:18808/sso-proxy/security/security/oauth/authorize
      scope: read, write
    resource:
      token-info-uri: http://localhost:18808/sso-proxy/security/security/oauth/check_token
logging:
  level.org.springframework.security: debug