spring:
  application:
    name: ms-inventory
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ms_inventory?characterEncoding=utf8
    username: ms_ivtr
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# redis config
redis:
  model: pool
  host-and-port: localhost:6379
  pass: test123456
  max-idle: 8
  max-total: 100
  max-wait-millis: 2000
# sso
security:
  oauth2:
    resource:
      jwt: # jwt使用这种方式来验证token
        key-uri: http://localhost:9998/oauth/token_key
# sso使用下面方式来验证token，这种方式和上面的jwt方式不可共存
#      token-info-uri: http://localhost:9999/security/oauth/check_token
#    client:
#      client-id: acme
#      client-secret: acmesecret
# log
logging:
  level:
    root: info