logging:
  level.org.springframework.security: debug
#security:
#  oauth2:
#    client:
#      client-id: mud
#      client-secret: mud
#      scope: read, write
#      auto-approve-scopes: .*
#    authorization:
#      check-token-access: permitAll()