spring:
  profiles:
    active: pro
mybatis:
  mapper-locations: classpath:META-INF/mybatis/sqlmap/*.xml
  type-aliases-package: com.tony.demo.microservice.mud.dao.entity
#security:
#  oauth2:
#    client:
#      client-id: mud
#      client-secret: mud
#      scope: read, write
#      auto-approve-scopes: .*
#    authorization:
#      check-token-access: permitAll()